apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "testChart.fullname" . }}-termination"
  labels:
    environment: staging
    app.kubernetes.io/name: "{{ template "testChart.name" . }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/component: sample
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: helm
    app: "{{ template "testChart.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service  }}"
    release: "{{ .Release.Name }}"
    {{- include "testChart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "testChart.selectorLabels" . | nindent 6 }}
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "helm-sample.local"
    - "helm-sample.local"
  - ip: "10.41.40.40"
    hostnames:
    - "helm-sample.remote"
    - "helm-sample.remote"      
  containers:
  - name: termination-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c", "sleep 10 && echo Sleep expired > /dev/termination-log"]
