apiVersion: v1
kind: Service
metadata:
  name: {{ include "testChart.fullname" . }}
  # See https://helm.sh/docs/chart_best_practices/labels/
  labels:
    environment: dev
    app.kubernetes.io/name: "{{ template "testChart.name" . }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    {{- include "testChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #targetPort: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector: {{- include "testChart.selectorLabels" . | nindent 4 }}
