---
version: '2'
# This is a sample .codeclimate.yml configured for Engine analysis on Code
# Climate Platform For an overview of the Code Climate Platform, see here:
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

# Under the engines key, you can configure which engines will analyze your repo.
# Each key is an engine name. For each value, you need to specify enabled: true
# to enable the engine as well as any other engines-specific configuration.

# For more details, see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
  # to turn on an engine, add it here and set enabled to `true`
  # to turn off an engine, set enabled to `false` or remove it
  rubocop:
    enabled: false
  semgrep:
    enabled: false
  bandit:
    enabled: false
  pylint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  bundler-audit:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
  fixme:
    enabled: true
    exclude_patterns:
      - config/engines.yml
  markdownlint:
    enabled: true
    checks:
      MD002: # "First header should be a h1 header"
        enabled: false
  shellcheck:
    enabled: true
exclude_patterns:
  - .direnv/**/*
  - .venv/**/*
  - .mypy_cache/
  - config/
  - db/
  - dist/
  - features/
  - node_modules/**/*
  - node_cache/**/*
  # - spec/**/*
  - test/spec/**/*
  - public/**
  - vendor/**
  - scripts/microscanner-wrapper/**
  - netsniff.js
  - mvnw
  - docker/target/**
