---
trustedRegistries:
  - docker.io
  - registry.gitlab.com
ignored:
  - DL3007
  - DL3016
  - DL3028
  - SC2086
  - SC2039
  - DL3059
#  - DL3018
label-schema:
  name: text
#  org.website: url
# strict-labels: true
