sudo: required
dist: travis_lts
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
#addons:
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable
language: node_js
node_js:
#  - "7"
  - "node"
branches:
  only:
    - master  
cache:
  directories:
    - "node_modules"
  yarn: true
env:
    - EMBER_VERSION=default
#    - EMBER_VERSION=release
#    - EMBER_VERSION=beta
#    - EMBER_VERSION=canary
matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

before_install:
  # setting the path for phantom.js 2.1.1
  #- export PATH=/usr/local/phantomjs-2.1.1/bin:$PATH
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export CHROME_BIN=chromium-browser    
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "npm config set spin false"
  #- "npm install -g npm@^2"
  #- "npm install -g npm"
  # C++14
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  #- sudo apt-get update
  - sudo apt-get install -y gcc-5.1 g++-5.1
  - sudo rm /bin/usr/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
    
before_script:
  - 'npm install -g bower karma grunt-cli jshint'
install:
  # C++14
  - sudo apt-get install -y -qq g++-5.1
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5.1 90
  - sudo apt-get install -y ruby-compass
  #- mkdir travis-phantomjs
  #- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  #- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  #- export PATH=$PWD/travis-phantomjs:$PATH
  #- travis_retry npm install bower
  #- travis_retry npm install grunt-cli
  - travis_retry npm install
  - bower install
#script:
#  - grunt
#  - ember test --server
