---
# Copyright Alban Andrieu 2013-2020
# Distributed under the GPL-3.0
# (See accompanying file LICENSE.md)

sudo: required
dist: travis_lts
#dist: bionic

jdk:
#  - oraclejdk8
#  - oraclejdk11
  - openjdk8
#  - openjdk11

addons:
  chrome: stable
  #firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
#    - ruby-compass

language: nodejs

node_js:
#  - "8"
  - "11"

compiler:
#  - clang
  - gcc

services:
  - docker
  - xvfb

cache:
  pip: true
  npm: true
  yarn: true
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2
    - node_modules
    - travis_phantomjs

env:
  matrix:
  - EMBER_VERSION=default
  global:
  - MOZ_HEADLESS=1
  - secure: AZtlXwv64rBSAE1L7cNGhGnXZxs+zrBrKqYfs1o0s9n+7bo6XDJtDtPCaNODonoXo9+WY0NpZErFUsx/FvCXhOgkjpMP1OLdi7iX2R7qMntl8YtDOWI8NCYggCIeqRG8EsN9hjL/6IClvkfudyDLV0aKUyWRrVzwciDsLhgStyo=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_VERSION=release
  - env: EMBER_VERSION=beta
  - env: EMBER_VERSION=canary

# See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-chrome-addon-in-the-headless-mode

before_install:
  #- export CHROME_BIN=chromium-browser
  - sudo apt-get install -qq xvfb
  - export DISPLAY=:99.0
  #- "sh -e /etc/init.d/xvfb start"
  #- sleep 3 # give xvfb some time to start

  - npm config set spin false
  #- 'gem install sass --version "=3.2.12"'
  #- 'gem install compass --version "=0.12.2"'
  - 'gem install sass'
  - 'gem install compass'
  - npm install -g bower karma grunt-cli jshint
  # Upgrade PhantomJS to v2.1.1.
  - "export PHANTOMJS_VERSION=2.1.1"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"

  - # start your web application and listen on `localhost`
  - # google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:9877 &

install:
  - npm set progress=false
  - npm install
  - travis_retry bower install
  - grunt prepare
  - grunt check
  - grunt default
  - grunt unit-test
  - grunt package
  # - grunt integration-test

branches:
  only:
  - master

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/47b10b81867bd0063cf5
    on_success: change
    on_failure: always
    on_start: false

#script:
#  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
#  - gcc --version
