---
version: '3.7'

services:

    prometheus:
      image: prom/prometheus:latest
      container_name: monitoring_prometheus
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus/
        - ./data/prometheus/data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      links:
        - cadvisor:monitoring_cadvisor
        - node-exporter:node-monitoring_node_exporter

    node-exporter:
      image: prom/node-exporter:latest
      container_name: monitoring_node_exporter
      restart: unless-stopped
      ports:
        - 9100:9100

  #   alertmanager:
  #     image: prom/alertmanager
  #     ports:
  #       - 9093:9093
  #     volumes:
  #       - ./alertmanager/:/etc/alertmanager/
  #     networks:
  #       - back-tier
  #     restart: always
  #     command:
  #       - '--config.file=/etc/alertmanager/config.yml'
  #       - '--storage.path=/alertmanager'
  # #    deploy:
  #      placement:
  #        constraints:
  #          - node.hostname == ${HOSTNAME}

    cadvisor:
      image: google/cadvisor:latest
      container_name: monitoring_cadvisor
      restart: unless-stopped
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      ports:
        - 7777:8080

    grafana:
      image: grafana/grafana:latest
      user: "1000"
      container_name: monitoring_grafana
      restart: unless-stopped
      links:
        - prometheus:monitoring_prometheus
      volumes:
        - ./data/grafana/data:/var/lib/grafana
        - ./data/grafana/provisioning/:/etc/grafana/provisioning/
        #- ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
        #- ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml. 1860
        #- ./grafana/grafana.ini:/etc/grafana/grafana.ini
        #- ./grafana/dashboards:/var/lib/grafana/dashboards
      environment:
         - GF_SECURITY_ADMIN_USER=admin
         - GF_SECURITY_ADMIN_PASSWORD=admin
         - GF_USERS_ALLOW_SIGN_UP=false
        #- GF_USERS_ALLOW_SIGN_UP=true
        #- GF_SECURITY_ADMIN_PASSWORD="secure_pass"
        #- GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      depends_on:
        - prometheus
      ports:
        - '3000:3000'
 #       - GF_SERVER_DOMAIN=myrul.com
 #       - GF_SMTP_ENABLED=true
 #       - GF_SMTP_HOST=smtp.gmail.com:587
 #       - GF_SMTP_USER=myadrress@gmail.com
 #       - GF_SMTP_PASSWORD=mypassword
 #       - GF_SMTP_FROM_ADDRESS=guillaume.denis@finastra.com
