apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testChart.fullname" . }}
  # See https://helm.sh/docs/chart_best_practices/labels/
  labels:
    environment: dev
    app.kubernetes.io/name: "{{ template "testChart.name" . }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/component: sample
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: helm
    app: "{{ template "testChart.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service  }}"
    release: "{{ .Release.Name }}"
    {{- include "testChart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "testChart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "testChart.selectorLabels" . | nindent 8 }}
        app: {{ template "testChart.name" . }}
        chart: {{ template "testChart.chart" . }}
        tier: frontend
        track: canary
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "testChart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      initContainers:
        - name: sleep
          image: debian:stretch
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - 'echo "create by init-container" > /secrets/file'
          volumeMounts:
            - mountPath: /secrets
              name: shared
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
