# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 7777

    static_configs:
         - targets: ['monitoring_cadvisor:8080']

  - job_name: 'node-exporter'

    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

    static_configs:
         - targets: ['monitoring_node_exporter:9100']

  - job_name: 'jenkins-albandrieu'
    metrics_path: '/prometheus/'
    #scheme: https
    #tls_config:
    #  insecure_skip_verify: true
    #bearer_token: <INSERT TOKEN HERE>
    static_configs:
        - targets: ['devops_jenkins:8080']
        #- targets: ['192.168.1.62:8686']
    # The Prometheus metrics plugin exposes metrics with the "job" label which are transformed into "exported_job".
    # Turn them into "jenkins_job" instead.
    metric_relabel_configs:
    - action: replace
      source_labels: [exported_job]
      target_label: jenkins_job
    - action: labeldrop
      regex: exported_job

  - job_name: 'jenkins-nabla'
    metrics_path: '/jenkins/prometheus/'
    #scheme: https
    #tls_config:
    #  insecure_skip_verify: true
    #bearer_token: <INSERT TOKEN HERE>
    static_configs:
        - targets: ['192.168.1.62:80']
    # The Prometheus metrics plugin exposes metrics with the "job" label which are transformed into "exported_job".
    # Turn them into "jenkins_job" instead.
    metric_relabel_configs:
    - action: replace
      source_labels: [exported_job]
      target_label: jenkins_job
    - action: labeldrop
      regex: exported_job

#  - job_name: 'freenas'
#    static_configs:
#         - targets: ['192.168.1.24:9103']
