---
schemaVersion: 2.0.0

commandTests:
  - name: check jenkins user
    command: whoami
    expectedOutput: [jenkins]
  - name: check jenkins uid/gid used for config generation
    command: id
    expectedOutput: [uid=2000.jenkins. gid=2000.docker. groups=2000.docker.*]
  - name: apt-get upgrade
    command: apt-get
    args: [-qqs, upgrade]
    excludedOutput: [.*Inst.*Security.* | .*Security.*Inst.*]
    excludedError: [.*Inst.*Security.* | .*Security.*Inst.*]

fileExistenceTests:
  - name: jenkins directory
    path: /home/jenkins
    shouldExist: true
    permissions: drwxrwxrwx
    uid: 2000

# - name: 'war file'
#   path: '/opt/test.war'
#   shouldExist: true
#   permissions: '-rw-r--r--'
##   uid: 0
#   uid: 2000

metadataTest:
  #  exposedPorts: [22]
  exposedPorts: []
  volumes: []
  cmd: [/opt/bin/entry_point.sh]
