---
name: Release Charts

on:
  push:
    branches: [master, main]
    paths-ignore:
      - "**.md"

jobs:
  release:
    if: github.actor != 'dependabot[bot]' && github.actor!= 'dependabot-preview[bot]'   # ignore the pull request which comes from user dependabot.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.1
        with:
          version: v3.4.0

      #- name: Add helm repositories
      #  run: |
      #    helm repo add bitnami https://charts.bitnami.com/bitnami
      #    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: packs/helm-sample
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
