---
name: Vault

on:
  push:
    branches: [master]
    # branches-ignore: "dependabot/**"
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 0 6 * * 3
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    name: Test vault
    #runs-on: self-hosted
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.7.3
        with:
          #url: https://vault-cluster.vault.aa257bb4-2600-4ef4-b9ce-a97076835404.aws.hashicorp.cloud:8200
          url: https://vault.albandrieu.com
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          #caCertificate: ${{ secrets.VAULT_CA_CERT }}
          namespace: admin
          #method: jwt
          jwtGithubAudience: sigstore # set the GitHub token's aud claim
          role: nabla
          #secrets: secret/data/test/webapp api-key | API_KEY;
          secrets: |
            nabla/data/scan/sonarcloud sonar-token | SONAR_TOKEN;
            secret/data/test/webapp api-key | API_KEY
      - name: Test printing your secret
        run: |
          echo $SONAR_TOKEN
          echo $API_KEY
